Bump the version of akka-http-circe
When I ran the tests, I was getting errors like:

    Uncaught error from thread [default-akka.actor.default-dispatcher-5]:
    java.lang.NoClassDefFoundError: akka/stream/actor/ActorSubscriber,
    shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
    for ActorSystem[default]

And I've seen errors like this before from mismatched versions of Akka.
v1.32.0 is what we use in the catalogue repo, so it's likely to be
compatible with our libs.